# Fix auction creation - handle empty responses + ensure route directory exists
# Run from: C:\Users\Anthony\artunderground
# Usage: PowerShell -ExecutionPolicy Bypass -File .\fix_auction.ps1

$ErrorActionPreference = "Stop"
function log($msg) { Write-Host ">> $msg" -ForegroundColor Green }
function Write-B64 {
  param([string]$RelPath, [string]$B64)
  $full = Join-Path (Get-Location) $RelPath
  $dir  = Split-Path $full -Parent
  if (!(Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
  [System.IO.File]::WriteAllBytes($full, [System.Convert]::FromBase64String($B64))
  log "Created $RelPath"
}

# Ensure the auctions API directory exists
$aucDir = Join-Path (Get-Location) "src\app\api\auctions"
if (!(Test-Path $aucDir)) { New-Item -ItemType Directory -Path $aucDir -Force | Out-Null; log "Created auctions API directory" }

$b = ""
$b += "aW1wb3J0IHsgTmV4dFJlcXVlc3QsIE5leHRSZXNwb25zZSB9IGZyb20gJ25leHQvc2VydmVyJwpp"
$b += "bXBvcnQgeyBjcmVhdGVTZXJ2ZXJTdXBhYmFzZUNsaWVudCB9IGZyb20gJ0AvbGliL3N1cGFiYXNl"
$b += "L3NlcnZlcicKaW1wb3J0IHsgeiB9IGZyb20gJ3pvZCcKCmNvbnN0IENyZWF0ZUF1Y3Rpb25TY2hl"
$b += "bWEgPSB6Lm9iamVjdCh7CiAgYXJ0d29ya19pZDogIHouc3RyaW5nKCkudXVpZCgpLAogIHJlc2Vy"
$b += "dmVfZ2JwOiB6Lm51bWJlcigpLnBvc2l0aXZlKCdSZXNlcnZlIHByaWNlIG11c3QgYmUgZ3JlYXRl"
$b += "ciB0aGFuIHplcm8nKSwKICBvcGVuc19hdDogICAgei5zdHJpbmcoKS5taW4oMSksCiAgY2xvc2Vz"
$b += "X2F0OiAgIHouc3RyaW5nKCkubWluKDEpLAp9KQoKZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIFBPU1Qo"
$b += "cmVxdWVzdDogTmV4dFJlcXVlc3QpIHsKICB0cnkgewogICAgY29uc3Qgc3VwYWJhc2UgPSBhd2Fp"
$b += "dCBjcmVhdGVTZXJ2ZXJTdXBhYmFzZUNsaWVudCgpCiAgICBjb25zdCB7IGRhdGE6IHsgdXNlciB9"
$b += "LCBlcnJvcjogYXV0aEVycm9yIH0gPSBhd2FpdCBzdXBhYmFzZS5hdXRoLmdldFVzZXIoKQogICAg"
$b += "aWYgKGF1dGhFcnJvciB8fCAhdXNlcikgewogICAgICByZXR1cm4gTmV4dFJlc3BvbnNlLmpzb24o"
$b += "eyBlcnJvcjogJ1VuYXV0aG9yaXplZCcgfSwgeyBzdGF0dXM6IDQwMSB9KQogICAgfQoKICAgIGNv"
$b += "bnN0IHsgZGF0YTogcHJvZmlsZSB9ID0gYXdhaXQgc3VwYWJhc2UKICAgICAgLmZyb20oJ3Byb2Zp"
$b += "bGVzJykuc2VsZWN0KCdpZCwgcm9sZXMnKS5lcSgnYXV0aF91c2VyX2lkJywgdXNlci5pZCkuc2lu"
$b += "Z2xlKCkKICAgIGlmICghcHJvZmlsZSB8fCAhcHJvZmlsZS5yb2xlcy5pbmNsdWRlcygnYXJ0aXN0"
$b += "JykpIHsKICAgICAgcmV0dXJuIE5leHRSZXNwb25zZS5qc29uKHsgZXJyb3I6ICdPbmx5IGFydGlz"
$b += "dHMgY2FuIGNyZWF0ZSBhdWN0aW9ucycgfSwgeyBzdGF0dXM6IDQwMyB9KQogICAgfQoKICAgIGxl"
$b += "dCBib2R5OiB1bmtub3duCiAgICB0cnkgewogICAgICBib2R5ID0gYXdhaXQgcmVxdWVzdC5qc29u"
$b += "KCkKICAgIH0gY2F0Y2ggewogICAgICByZXR1cm4gTmV4dFJlc3BvbnNlLmpzb24oeyBlcnJvcjog"
$b += "J0ludmFsaWQgcmVxdWVzdCBib2R5JyB9LCB7IHN0YXR1czogNDAwIH0pCiAgICB9CgogICAgY29u"
$b += "c3QgcGFyc2VkID0gQ3JlYXRlQXVjdGlvblNjaGVtYS5zYWZlUGFyc2UoYm9keSkKICAgIGlmICgh"
$b += "cGFyc2VkLnN1Y2Nlc3MpIHsKICAgICAgY29uc3QgbXNnID0gcGFyc2VkLmVycm9yLmVycm9yc1sw"
$b += "XT8ubWVzc2FnZSA/PyAnSW52YWxpZCBkYXRhJwogICAgICByZXR1cm4gTmV4dFJlc3BvbnNlLmpz"
$b += "b24oeyBlcnJvcjogbXNnIH0sIHsgc3RhdHVzOiA0MDAgfSkKICAgIH0KCiAgICBjb25zdCB7IGRh"
$b += "dGE6IGFydHdvcmsgfSA9IGF3YWl0IHN1cGFiYXNlCiAgICAgIC5mcm9tKCdhcnR3b3JrcycpLnNl"
$b += "bGVjdCgnaWQsIHN0YXR1cywgYXJ0aXN0X2lkJykKICAgICAgLmVxKCdpZCcsIHBhcnNlZC5kYXRh"
$b += "LmFydHdvcmtfaWQpLnNpbmdsZSgpCgogICAgaWYgKCFhcnR3b3JrKSB7CiAgICAgIHJldHVybiBO"
$b += "ZXh0UmVzcG9uc2UuanNvbih7IGVycm9yOiAnQXJ0d29yayBub3QgZm91bmQnIH0sIHsgc3RhdHVz"
$b += "OiA0MDQgfSkKICAgIH0KICAgIGlmIChhcnR3b3JrLmFydGlzdF9pZCAhPT0gcHJvZmlsZS5pZCkg"
$b += "ewogICAgICByZXR1cm4gTmV4dFJlc3BvbnNlLmpzb24oeyBlcnJvcjogJ05vdCB5b3VyIGFydHdv"
$b += "cmsnIH0sIHsgc3RhdHVzOiA0MDMgfSkKICAgIH0KICAgIGlmICghWydsaXN0ZWQnLCAnZHJhZnQn"
$b += "XS5pbmNsdWRlcyhhcnR3b3JrLnN0YXR1cykpIHsKICAgICAgcmV0dXJuIE5leHRSZXNwb25zZS5q"
$b += "c29uKHsgZXJyb3I6ICdBcnR3b3JrIGlzIGFscmVhZHkgaW4gYXVjdGlvbiBvciBzb2xkJyB9LCB7"
$b += "IHN0YXR1czogNDA5IH0pCiAgICB9CgogICAgY29uc3QgeyBkYXRhOiBhdWN0aW9uLCBlcnJvcjog"
$b += "YXVjRXJyb3IgfSA9IGF3YWl0IHN1cGFiYXNlCiAgICAgIC5mcm9tKCdhdWN0aW9ucycpCiAgICAg"
$b += "IC5pbnNlcnQoewogICAgICAgIGFydHdvcmtfaWQ6ICBwYXJzZWQuZGF0YS5hcnR3b3JrX2lkLAog"
$b += "ICAgICAgIHNlbGxlcl9pZDogICBwcm9maWxlLmlkLAogICAgICAgIHJlc2VydmVfZ2JwOiBwYXJz"
$b += "ZWQuZGF0YS5yZXNlcnZlX2dicCwKICAgICAgICBvcGVuc19hdDogICAgcGFyc2VkLmRhdGEub3Bl"
$b += "bnNfYXQsCiAgICAgICAgY2xvc2VzX2F0OiAgIHBhcnNlZC5kYXRhLmNsb3Nlc19hdCwKICAgICAg"
$b += "ICBzdGF0dXM6ICAgICAgJ2xpdmUnLAogICAgICB9KQogICAgICAuc2VsZWN0KCkKICAgICAgLnNp"
$b += "bmdsZSgpCgogICAgaWYgKGF1Y0Vycm9yKSB7CiAgICAgIGNvbnNvbGUuZXJyb3IoJ0F1Y3Rpb24g"
$b += "Y3JlYXRpb24gZXJyb3I6JywgYXVjRXJyb3IpCiAgICAgIHJldHVybiBOZXh0UmVzcG9uc2UuanNv"
$b += "bih7IGVycm9yOiAnRGF0YWJhc2UgZXJyb3I6ICcgKyBhdWNFcnJvci5tZXNzYWdlIH0sIHsgc3Rh"
$b += "dHVzOiA1MDAgfSkKICAgIH0KCiAgICBhd2FpdCBzdXBhYmFzZS5mcm9tKCdhcnR3b3JrcycpCiAg"
$b += "ICAgIC51cGRhdGUoeyBzdGF0dXM6ICdpbl9hdWN0aW9uJyB9KQogICAgICAuZXEoJ2lkJywgcGFy"
$b += "c2VkLmRhdGEuYXJ0d29ya19pZCkKCiAgICBjb25zdCB7IGRhdGE6IGF3IH0gPSBhd2FpdCBzdXBh"
$b += "YmFzZS5mcm9tKCdhcnR3b3JrcycpCiAgICAgIC5zZWxlY3QoJ3Byb3ZlbmFuY2UnKS5lcSgnaWQn"
$b += "LCBwYXJzZWQuZGF0YS5hcnR3b3JrX2lkKS5zaW5nbGUoKQogICAgaWYgKGF3KSB7CiAgICAgIGF3"
$b += "YWl0IHN1cGFiYXNlLmZyb20oJ2FydHdvcmtzJykudXBkYXRlKHsKICAgICAgICBwcm92ZW5hbmNl"
$b += "OiBbLi4uKGF3LnByb3ZlbmFuY2UgYXMgb2JqZWN0W10pLCB7CiAgICAgICAgICB0eXBlOiAnbGlz"
$b += "dGVkJywKICAgICAgICAgIGRlc2NyaXB0aW9uOiAnTGlzdGVkIGZvciBhdWN0aW9uIG9uIEFydFVO"
$b += "REVSR1JPVU5EJywKICAgICAgICAgIGRhdGU6IG5ldyBEYXRlKCkudG9JU09TdHJpbmcoKS5zcGxp"
$b += "dCgnVCcpWzBdLAogICAgICAgIH1dCiAgICAgIH0pLmVxKCdpZCcsIHBhcnNlZC5kYXRhLmFydHdv"
$b += "cmtfaWQpCiAgICB9CgogICAgcmV0dXJuIE5leHRSZXNwb25zZS5qc29uKHsgYXVjdGlvbiB9LCB7"
$b += "IHN0YXR1czogMjAxIH0pCgogIH0gY2F0Y2ggKGVycikgewogICAgY29uc29sZS5lcnJvcignVW5o"
$b += "YW5kbGVkIGF1Y3Rpb24gcm91dGUgZXJyb3I6JywgZXJyKQogICAgcmV0dXJuIE5leHRSZXNwb25z"
$b += "ZS5qc29uKHsgZXJyb3I6ICdJbnRlcm5hbCBzZXJ2ZXIgZXJyb3InIH0sIHsgc3RhdHVzOiA1MDAg"
$b += "fSkKICB9Cn0K"
Write-B64 "src\app\api\auctions\route.ts" $b

$b = ""
$b += "J3VzZSBjbGllbnQnCgppbXBvcnQgeyB1c2VTdGF0ZSB9IGZyb20gJ3JlYWN0JwppbXBvcnQgeyB1"
$b += "c2VSb3V0ZXIgfSBmcm9tICduZXh0L25hdmlnYXRpb24nCgppbnRlcmZhY2UgUHJvcHMgewogIGFy"
$b += "dHdvcmtJZDogICAgc3RyaW5nCiAgYXJ0d29ya1RpdGxlOiBzdHJpbmcKfQoKZXhwb3J0IGZ1bmN0"
$b += "aW9uIENyZWF0ZUF1Y3Rpb25CdXR0b24oeyBhcnR3b3JrSWQsIGFydHdvcmtUaXRsZSB9OiBQcm9w"
$b += "cykgewogIGNvbnN0IHJvdXRlciAgPSB1c2VSb3V0ZXIoKQogIGNvbnN0IFtvcGVuLCAgICBzZXRP"
$b += "cGVuXSAgICA9IHVzZVN0YXRlKGZhbHNlKQogIGNvbnN0IFtyZXNlcnZlLCBzZXRSZXNlcnZlXSA9"
$b += "IHVzZVN0YXRlKCcnKQogIGNvbnN0IFtkYXlzLCAgICBzZXREYXlzXSAgICA9IHVzZVN0YXRlKCc3"
$b += "JykKICBjb25zdCBbbG9hZGluZywgc2V0TG9hZGluZ10gPSB1c2VTdGF0ZShmYWxzZSkKICBjb25z"
$b += "dCBbZXJyb3IsICAgc2V0RXJyb3JdICAgPSB1c2VTdGF0ZTxzdHJpbmcgfCBudWxsPihudWxsKQoK"
$b += "ICBhc3luYyBmdW5jdGlvbiBoYW5kbGVDcmVhdGUoKSB7CiAgICBjb25zdCByZXNlcnZlTnVtID0g"
$b += "cGFyc2VGbG9hdChyZXNlcnZlKQogICAgaWYgKCFyZXNlcnZlLnRyaW0oKSB8fCBpc05hTihyZXNl"
$b += "cnZlTnVtKSB8fCByZXNlcnZlTnVtIDw9IDApIHsKICAgICAgc2V0RXJyb3IoJ1BsZWFzZSBlbnRl"
$b += "ciBhIHZhbGlkIHJlc2VydmUgcHJpY2UgZ3JlYXRlciB0aGFuIHplcm8nKQogICAgICByZXR1cm4K"
$b += "ICAgIH0KCiAgICBzZXRMb2FkaW5nKHRydWUpCiAgICBzZXRFcnJvcihudWxsKQoKICAgIGNvbnN0"
$b += "IG9wZW5zQXQgID0gbmV3IERhdGUoKQogICAgY29uc3QgY2xvc2VzQXQgPSBuZXcgRGF0ZSgpCiAg"
$b += "ICBjbG9zZXNBdC5zZXREYXRlKGNsb3Nlc0F0LmdldERhdGUoKSArIHBhcnNlSW50KGRheXMpKQoK"
$b += "ICAgIHRyeSB7CiAgICAgIGNvbnN0IHJlcyA9IGF3YWl0IGZldGNoKCcvYXBpL2F1Y3Rpb25zJywg"
$b += "ewogICAgICAgIG1ldGhvZDogICdQT1NUJywKICAgICAgICBoZWFkZXJzOiB7ICdDb250ZW50LVR5"
$b += "cGUnOiAnYXBwbGljYXRpb24vanNvbicgfSwKICAgICAgICBib2R5OiBKU09OLnN0cmluZ2lmeSh7"
$b += "CiAgICAgICAgICBhcnR3b3JrX2lkOiAgYXJ0d29ya0lkLAogICAgICAgICAgcmVzZXJ2ZV9nYnA6"
$b += "IHJlc2VydmVOdW0sCiAgICAgICAgICBvcGVuc19hdDogICAgb3BlbnNBdC50b0lTT1N0cmluZygp"
$b += "LAogICAgICAgICAgY2xvc2VzX2F0OiAgIGNsb3Nlc0F0LnRvSVNPU3RyaW5nKCksCiAgICAgICAg"
$b += "fSksCiAgICAgIH0pCgogICAgICAvLyBTYWZlbHkgcGFyc2UgcmVzcG9uc2UgLSBoYW5kbGUgZW1w"
$b += "dHkgb3Igbm9uLUpTT04gYm9kaWVzCiAgICAgIGxldCBkYXRhOiBhbnkgPSB7fQogICAgICBjb25z"
$b += "dCB0ZXh0ID0gYXdhaXQgcmVzLnRleHQoKQogICAgICBpZiAodGV4dCkgewogICAgICAgIHRyeSB7"
$b += "IGRhdGEgPSBKU09OLnBhcnNlKHRleHQpIH0gY2F0Y2ggeyBkYXRhID0geyBlcnJvcjogJ1NlcnZl"
$b += "ciBlcnJvciAoc3RhdHVzICcgKyByZXMuc3RhdHVzICsgJyknIH0gfQogICAgICB9CgogICAgICBp"
$b += "ZiAoIXJlcy5vaykgewogICAgICAgIHNldEVycm9yKGRhdGEuZXJyb3IgPz8gJ0ZhaWxlZCB0byBj"
$b += "cmVhdGUgYXVjdGlvbiAoc3RhdHVzICcgKyByZXMuc3RhdHVzICsgJyknKQogICAgICAgIHNldExv"
$b += "YWRpbmcoZmFsc2UpCiAgICAgICAgcmV0dXJuCiAgICAgIH0KCiAgICAgIHNldE9wZW4oZmFsc2Up"
$b += "CiAgICAgIHNldFJlc2VydmUoJycpCiAgICAgIHJvdXRlci5yZWZyZXNoKCkKCiAgICB9IGNhdGNo"
$b += "IChlcnIpIHsKICAgICAgc2V0RXJyb3IoJ05ldHdvcmsgZXJyb3IgLSBwbGVhc2UgdHJ5IGFnYWlu"
$b += "JykKICAgICAgc2V0TG9hZGluZyhmYWxzZSkKICAgIH0KICB9CgogIGlmICghb3BlbikgcmV0dXJu"
$b += "ICgKICAgIDxidXR0b24gb25DbGljaz17KCkgPT4gc2V0T3Blbih0cnVlKX0KICAgICAgc3R5bGU9"
$b += "e3sgY29sb3I6ICcjRDg1QTMwJywgYm9yZGVyQ29sb3I6ICcjRDg1QTMwJywgYmFja2dyb3VuZDog"
$b += "JyMxYTBhMDgnLCBmb250U2l6ZTogJzEwcHgnIH19CiAgICAgIGNsYXNzTmFtZT0nYm9yZGVyIHJv"
$b += "dW5kZWQgcHgtMS41IHB5LTAuNSBmb250LW1lZGl1bSBob3ZlcjpvcGFjaXR5LTgwIHRyYW5zaXRp"
$b += "b24tb3BhY2l0eSB3aGl0ZXNwYWNlLW5vd3JhcCc+CiAgICAgIEF1Y3Rpb24KICAgIDwvYnV0dG9u"
$b += "PgogICkKCiAgcmV0dXJuICgKICAgIDxkaXYKICAgICAgc3R5bGU9e3sgcG9zaXRpb246ICdmaXhl"
$b += "ZCcsIGluc2V0OiAwLCBiYWNrZ3JvdW5kOiAncmdiYSgwLDAsMCwwLjgpJywgekluZGV4OiA1MCB9"
$b += "fQogICAgICBjbGFzc05hbWU9J2ZsZXggaXRlbXMtY2VudGVyIGp1c3RpZnktY2VudGVyIHAtNCcK"
$b += "ICAgICAgb25DbGljaz17ZSA9PiB7IGlmIChlLnRhcmdldCA9PT0gZS5jdXJyZW50VGFyZ2V0KSB7"
$b += "IHNldE9wZW4oZmFsc2UpOyBzZXRFcnJvcihudWxsKSB9IH19PgogICAgICA8ZGl2IHN0eWxlPXt7"
$b += "IGJhY2tncm91bmQ6ICd2YXIoLS1iZy1jYXJkKScsIGJvcmRlckNvbG9yOiAndmFyKC0tYm9yZGVy"
$b += "KScsIHdpZHRoOiAnMTAwJScsIG1heFdpZHRoOiAnMzYwcHgnIH19CiAgICAgICAgY2xhc3NOYW1l"
$b += "PSdib3JkZXIgcm91bmRlZC0yeGwgcC02Jz4KCiAgICAgICAgPGgyIHN0eWxlPXt7IGNvbG9yOiAn"
$b += "dmFyKC0tdGV4dC1wcmltYXJ5KScgfX0gY2xhc3NOYW1lPSd0ZXh0LWxnIGZvbnQtbWVkaXVtIG1i"
$b += "LTEnPgogICAgICAgICAgQ3JlYXRlIGF1Y3Rpb24KICAgICAgICA8L2gyPgogICAgICAgIDxwIHN0"
$b += "eWxlPXt7IGNvbG9yOiAndmFyKC0tdGV4dC1tdXRlZCknIH19IGNsYXNzTmFtZT0ndGV4dC1zbSBt"
$b += "Yi01IHRydW5jYXRlJz4KICAgICAgICAgIHthcnR3b3JrVGl0bGV9CiAgICAgICAgPC9wPgoKICAg"
$b += "ICAgICA8ZGl2IGNsYXNzTmFtZT0nc3BhY2UteS00Jz4KICAgICAgICAgIDxkaXY+CiAgICAgICAg"
$b += "ICAgIDxsYWJlbCBzdHlsZT17eyBjb2xvcjogJ3ZhcigtLXRleHQtc2Vjb25kYXJ5KScsIGRpc3Bs"
$b += "YXk6ICdibG9jaycsIGZvbnRTaXplOiAnMTJweCcsIG1hcmdpbkJvdHRvbTogJzZweCcgfX0+CiAg"
$b += "ICAgICAgICAgICAgUmVzZXJ2ZSBwcmljZSAoR0JQKSAqCiAgICAgICAgICAgIDwvbGFiZWw+CiAg"
$b += "ICAgICAgICAgIDxpbnB1dCB0eXBlPSdudW1iZXInIHZhbHVlPXtyZXNlcnZlfSBvbkNoYW5nZT17"
$b += "ZSA9PiBzZXRSZXNlcnZlKGUudGFyZ2V0LnZhbHVlKX0KICAgICAgICAgICAgICBwbGFjZWhvbGRl"
$b += "cj0nZS5nLiA1MDAnIG1pbj0nMScgc3RlcD0nMScKICAgICAgICAgICAgICBzdHlsZT17ewogICAg"
$b += "ICAgICAgICAgICAgd2lkdGg6ICcxMDAlJywgcGFkZGluZzogJzEwcHggMTJweCcsIGJvcmRlclJh"
$b += "ZGl1czogJzhweCcsCiAgICAgICAgICAgICAgICBib3JkZXI6ICcwLjVweCBzb2xpZCB2YXIoLS1i"
$b += "b3JkZXIpJywgYmFja2dyb3VuZDogJ3ZhcigtLWJnLXNlY29uZGFyeSknLAogICAgICAgICAgICAg"
$b += "ICAgY29sb3I6ICd2YXIoLS10ZXh0LXByaW1hcnkpJywgZm9udFNpemU6ICcxNHB4JywKICAgICAg"
$b += "ICAgICAgICB9fSAvPgogICAgICAgICAgICA8cCBzdHlsZT17eyBjb2xvcjogJ3ZhcigtLXRleHQt"
$b += "bXV0ZWQpJywgZm9udFNpemU6ICcxMXB4JywgbWFyZ2luVG9wOiAnNHB4JyB9fT4KICAgICAgICAg"
$b += "ICAgICBNaW5pbXVtIHByaWNlIHlvdSB3aWxsIGFjY2VwdC4gQmlkZGluZyBzdGFydHMgaGVyZS4K"
$b += "ICAgICAgICAgICAgPC9wPgogICAgICAgICAgPC9kaXY+CgogICAgICAgICAgPGRpdj4KICAgICAg"
$b += "ICAgICAgPGxhYmVsIHN0eWxlPXt7IGNvbG9yOiAndmFyKC0tdGV4dC1zZWNvbmRhcnkpJywgZGlz"
$b += "cGxheTogJ2Jsb2NrJywgZm9udFNpemU6ICcxMnB4JywgbWFyZ2luQm90dG9tOiAnNnB4JyB9fT4K"
$b += "ICAgICAgICAgICAgICBBdWN0aW9uIGR1cmF0aW9uCiAgICAgICAgICAgIDwvbGFiZWw+CiAgICAg"
$b += "ICAgICAgIDxzZWxlY3QgdmFsdWU9e2RheXN9IG9uQ2hhbmdlPXtlID0+IHNldERheXMoZS50YXJn"
$b += "ZXQudmFsdWUpfQogICAgICAgICAgICAgIHN0eWxlPXt7CiAgICAgICAgICAgICAgICB3aWR0aDog"
$b += "JzEwMCUnLCBwYWRkaW5nOiAnMTBweCAxMnB4JywgYm9yZGVyUmFkaXVzOiAnOHB4JywKICAgICAg"
$b += "ICAgICAgICAgIGJvcmRlcjogJzAuNXB4IHNvbGlkIHZhcigtLWJvcmRlciknLCBiYWNrZ3JvdW5k"
$b += "OiAndmFyKC0tYmctc2Vjb25kYXJ5KScsCiAgICAgICAgICAgICAgICBjb2xvcjogJ3ZhcigtLXRl"
$b += "eHQtcHJpbWFyeSknLCBmb250U2l6ZTogJzE0cHgnLAogICAgICAgICAgICAgIH19PgogICAgICAg"
$b += "ICAgICAgIDxvcHRpb24gdmFsdWU9JzEnPjEgZGF5PC9vcHRpb24+CiAgICAgICAgICAgICAgPG9w"
$b += "dGlvbiB2YWx1ZT0nMyc+MyBkYXlzPC9vcHRpb24+CiAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1"
$b += "ZT0nNyc+NyBkYXlzPC9vcHRpb24+CiAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0nMTQnPjE0"
$b += "IGRheXM8L29wdGlvbj4KICAgICAgICAgICAgPC9zZWxlY3Q+CiAgICAgICAgICA8L2Rpdj4KCiAg"
$b += "ICAgICAgICA8ZGl2IHN0eWxlPXt7IGJhY2tncm91bmQ6ICd2YXIoLS1iZy1zZWNvbmRhcnkpJywg"
$b += "Ym9yZGVyQ29sb3I6ICd2YXIoLS1ib3JkZXIpJywgYm9yZGVyUmFkaXVzOiAnOHB4JywgcGFkZGlu"
$b += "ZzogJzEwcHggMTJweCcsIGJvcmRlcjogJzAuNXB4IHNvbGlkJyB9fT4KICAgICAgICAgICAgPGRp"
$b += "diBjbGFzc05hbWU9J2ZsZXgganVzdGlmeS1iZXR3ZWVuIHRleHQteHMgbWItMSc+CiAgICAgICAg"
$b += "ICAgICAgPHNwYW4gc3R5bGU9e3sgY29sb3I6ICd2YXIoLS10ZXh0LW11dGVkKScgfX0+UGxhdGZv"
$b += "cm0gZmVlPC9zcGFuPgogICAgICAgICAgICAgIDxzcGFuIHN0eWxlPXt7IGNvbG9yOiAndmFyKC0t"
$b += "dGV4dC1zZWNvbmRhcnkpJyB9fT4xMiUgb2YgaGFtbWVyIHByaWNlPC9zcGFuPgogICAgICAgICAg"
$b += "ICA8L2Rpdj4KICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9J2ZsZXgganVzdGlmeS1iZXR3ZWVu"
$b += "IHRleHQteHMnPgogICAgICAgICAgICAgIDxzcGFuIHN0eWxlPXt7IGNvbG9yOiAndmFyKC0tdGV4"
$b += "dC1tdXRlZCknIH19PkJ1eWVyJ3MgcHJlbWl1bTwvc3Bhbj4KICAgICAgICAgICAgICA8c3BhbiBz"
$b += "dHlsZT17eyBjb2xvcjogJ3ZhcigtLXRleHQtc2Vjb25kYXJ5KScgfX0+VEJDPC9zcGFuPgogICAg"
$b += "ICAgICAgICA8L2Rpdj4KICAgICAgICAgIDwvZGl2PgoKICAgICAgICAgIHtlcnJvciAmJiAoCiAg"
$b += "ICAgICAgICAgIDxkaXYgc3R5bGU9e3sgYmFja2dyb3VuZDogJyMxYTA4MDgnLCBib3JkZXJDb2xv"
$b += "cjogJyNEODVBMzAnLCBjb2xvcjogJyNEODVBMzAnLCBwYWRkaW5nOiAnOHB4IDEycHgnLCBib3Jk"
$b += "ZXJSYWRpdXM6ICc4cHgnLCBib3JkZXI6ICcwLjVweCBzb2xpZCcsIGZvbnRTaXplOiAnMTNweCcg"
$b += "fX0+CiAgICAgICAgICAgICAge2Vycm9yfQogICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICl9"
$b += "CgogICAgICAgICAgPGRpdiBzdHlsZT17eyBkaXNwbGF5OiAnZmxleCcsIGdhcDogJzEwcHgnIH19"
$b += "PgogICAgICAgICAgICA8YnV0dG9uIG9uQ2xpY2s9eygpID0+IHsgc2V0T3BlbihmYWxzZSk7IHNl"
$b += "dEVycm9yKG51bGwpIH19CiAgICAgICAgICAgICAgc3R5bGU9e3sgZmxleDogMSwgcGFkZGluZzog"
$b += "JzEwcHgnLCBib3JkZXJSYWRpdXM6ICc4cHgnLCBmb250U2l6ZTogJzEzcHgnLCBib3JkZXI6ICcw"
$b += "LjVweCBzb2xpZCB2YXIoLS1ib3JkZXIpJywgYmFja2dyb3VuZDogJ3RyYW5zcGFyZW50JywgY29s"
$b += "b3I6ICd2YXIoLS10ZXh0LXNlY29uZGFyeSknIH19PgogICAgICAgICAgICAgIENhbmNlbAogICAg"
$b += "ICAgICAgICA8L2J1dHRvbj4KICAgICAgICAgICAgPGJ1dHRvbiBvbkNsaWNrPXtoYW5kbGVDcmVh"
$b += "dGV9IGRpc2FibGVkPXtsb2FkaW5nfQogICAgICAgICAgICAgIHN0eWxlPXt7IGZsZXg6IDEsIHBh"
$b += "ZGRpbmc6ICcxMHB4JywgYm9yZGVyUmFkaXVzOiAnOHB4JywgZm9udFNpemU6ICcxM3B4JywgZm9u"
$b += "dFdlaWdodDogNTAwLCBiYWNrZ3JvdW5kOiAndmFyKC0tcHVycGxlKScsIGNvbG9yOiAnd2hpdGUn"
$b += "LCBvcGFjaXR5OiBsb2FkaW5nID8gMC42IDogMSB9fT4KICAgICAgICAgICAgICB7bG9hZGluZyA/"
$b += "ICdDcmVhdGluZy4uLicgOiAnU3RhcnQgYXVjdGlvbid9CiAgICAgICAgICAgIDwvYnV0dG9uPgog"
$b += "ICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9kaXY+CiAgICAgIDwvZGl2PgogICAgPC9kaXY+CiAg"
$b += "KQp9Cg=="
Write-B64 "src\components\CreateAuctionButton.tsx" $b

Write-Host ""
Write-Host "Fixed! Verifying files exist..." -ForegroundColor Green
$routePath = Join-Path (Get-Location) "src\app\api\auctions\route.ts"
if (Test-Path $routePath) {
  Write-Host "  route.ts found" -ForegroundColor Green
} else {
  Write-Host "  ERROR: route.ts not found!" -ForegroundColor Red
}
Write-Host ""
Write-Host "Dashboard: http://localhost:3000/dashboard" -ForegroundColor Cyan
Write-Host ""