# Fix auction route - better error handling and UUID comparison
# Usage: PowerShell -ExecutionPolicy Bypass -File .\fix_auction2.ps1

$ErrorActionPreference = "Stop"
$b = ""
$b += "aW1wb3J0IHsgTmV4dFJlcXVlc3QsIE5leHRSZXNwb25zZSB9IGZyb20gJ25leHQvc2VydmVyJwpp"
$b += "bXBvcnQgeyBjcmVhdGVTZXJ2ZXJTdXBhYmFzZUNsaWVudCB9IGZyb20gJ0AvbGliL3N1cGFiYXNl"
$b += "L3NlcnZlcicKaW1wb3J0IHsgeiB9IGZyb20gJ3pvZCcKCmNvbnN0IENyZWF0ZUF1Y3Rpb25TY2hl"
$b += "bWEgPSB6Lm9iamVjdCh7CiAgYXJ0d29ya19pZDogIHouc3RyaW5nKCkudXVpZCgpLAogIHJlc2Vy"
$b += "dmVfZ2JwOiB6Lm51bWJlcigpLnBvc2l0aXZlKCksCiAgb3BlbnNfYXQ6ICAgIHouc3RyaW5nKCku"
$b += "bWluKDEpLAogIGNsb3Nlc19hdDogICB6LnN0cmluZygpLm1pbigxKSwKfSkKCmV4cG9ydCBhc3lu"
$b += "YyBmdW5jdGlvbiBQT1NUKHJlcXVlc3Q6IE5leHRSZXF1ZXN0KSB7CiAgdHJ5IHsKICAgIGNvbnN0"
$b += "IHN1cGFiYXNlID0gYXdhaXQgY3JlYXRlU2VydmVyU3VwYWJhc2VDbGllbnQoKQoKICAgIGNvbnN0"
$b += "IHsgZGF0YTogeyB1c2VyIH0sIGVycm9yOiBhdXRoRXJyb3IgfSA9IGF3YWl0IHN1cGFiYXNlLmF1"
$b += "dGguZ2V0VXNlcigpCiAgICBpZiAoYXV0aEVycm9yIHx8ICF1c2VyKSB7CiAgICAgIHJldHVybiBO"
$b += "ZXh0UmVzcG9uc2UuanNvbih7IGVycm9yOiAnVW5hdXRob3JpemVkJyB9LCB7IHN0YXR1czogNDAx"
$b += "IH0pCiAgICB9CgogICAgY29uc3QgeyBkYXRhOiBwcm9maWxlLCBlcnJvcjogcHJvZmlsZUVycm9y"
$b += "IH0gPSBhd2FpdCBzdXBhYmFzZQogICAgICAuZnJvbSgncHJvZmlsZXMnKS5zZWxlY3QoJ2lkLCBy"
$b += "b2xlcycpLmVxKCdhdXRoX3VzZXJfaWQnLCB1c2VyLmlkKS5zaW5nbGUoKQoKICAgIGlmIChwcm9m"
$b += "aWxlRXJyb3IgfHwgIXByb2ZpbGUpIHsKICAgICAgcmV0dXJuIE5leHRSZXNwb25zZS5qc29uKHsg"
$b += "ZXJyb3I6ICdQcm9maWxlIG5vdCBmb3VuZCcgfSwgeyBzdGF0dXM6IDQwNCB9KQogICAgfQoKICAg"
$b += "IGlmICghcHJvZmlsZS5yb2xlcy5pbmNsdWRlcygnYXJ0aXN0JykpIHsKICAgICAgcmV0dXJuIE5l"
$b += "eHRSZXNwb25zZS5qc29uKHsgZXJyb3I6ICdPbmx5IGFydGlzdHMgY2FuIGNyZWF0ZSBhdWN0aW9u"
$b += "cycgfSwgeyBzdGF0dXM6IDQwMyB9KQogICAgfQoKICAgIGxldCBib2R5OiB1bmtub3duCiAgICB0"
$b += "cnkgewogICAgICBib2R5ID0gYXdhaXQgcmVxdWVzdC5qc29uKCkKICAgIH0gY2F0Y2ggewogICAg"
$b += "ICByZXR1cm4gTmV4dFJlc3BvbnNlLmpzb24oeyBlcnJvcjogJ0ludmFsaWQgcmVxdWVzdCBib2R5"
$b += "JyB9LCB7IHN0YXR1czogNDAwIH0pCiAgICB9CgogICAgY29uc3QgcGFyc2VkID0gQ3JlYXRlQXVj"
$b += "dGlvblNjaGVtYS5zYWZlUGFyc2UoYm9keSkKICAgIGlmICghcGFyc2VkLnN1Y2Nlc3MpIHsKICAg"
$b += "ICAgcmV0dXJuIE5leHRSZXNwb25zZS5qc29uKAogICAgICAgIHsgZXJyb3I6IHBhcnNlZC5lcnJv"
$b += "ci5lcnJvcnMubWFwKGUgPT4gZS5tZXNzYWdlKS5qb2luKCcsICcpIH0sCiAgICAgICAgeyBzdGF0"
$b += "dXM6IDQwMCB9CiAgICAgICkKICAgIH0KCiAgICBjb25zdCB7IGFydHdvcmtfaWQsIHJlc2VydmVf"
$b += "Z2JwLCBvcGVuc19hdCwgY2xvc2VzX2F0IH0gPSBwYXJzZWQuZGF0YQoKICAgIC8vIEZldGNoIGFy"
$b += "dHdvcmsgd2l0aG91dCBvd25lcnNoaXAgY2hlY2sgZmlyc3QgdG8gc2VlIHdoYXQgd2UgZ2V0CiAg"
$b += "ICBjb25zdCB7IGRhdGE6IGFydHdvcmssIGVycm9yOiBhcnR3b3JrRXJyb3IgfSA9IGF3YWl0IHN1"
$b += "cGFiYXNlCiAgICAgIC5mcm9tKCdhcnR3b3JrcycpCiAgICAgIC5zZWxlY3QoJ2lkLCBzdGF0dXMs"
$b += "IGFydGlzdF9pZCcpCiAgICAgIC5lcSgnaWQnLCBhcnR3b3JrX2lkKQogICAgICAuc2luZ2xlKCkK"
$b += "CiAgICBpZiAoYXJ0d29ya0Vycm9yIHx8ICFhcnR3b3JrKSB7CiAgICAgIHJldHVybiBOZXh0UmVz"
$b += "cG9uc2UuanNvbigKICAgICAgICB7IGVycm9yOiAnQXJ0d29yayBub3QgZm91bmQnIH0sCiAgICAg"
$b += "ICAgeyBzdGF0dXM6IDQwNCB9CiAgICAgICkKICAgIH0KCiAgICAvLyBDb21wYXJlIGFzIHRyaW1t"
$b += "ZWQgc3RyaW5ncyB0byBhdm9pZCB3aGl0ZXNwYWNlIGlzc3VlcwogICAgY29uc3QgYXJ0d29ya0Fy"
$b += "dGlzdElkID0gU3RyaW5nKGFydHdvcmsuYXJ0aXN0X2lkKS50cmltKCkKICAgIGNvbnN0IHByb2Zp"
$b += "bGVJZCAgICAgICA9IFN0cmluZyhwcm9maWxlLmlkKS50cmltKCkKCiAgICBpZiAoYXJ0d29ya0Fy"
$b += "dGlzdElkICE9PSBwcm9maWxlSWQpIHsKICAgICAgcmV0dXJuIE5leHRSZXNwb25zZS5qc29uKAog"
$b += "ICAgICAgIHsgZXJyb3I6ICdZb3UgZG8gbm90IG93biB0aGlzIGFydHdvcmsnIH0sCiAgICAgICAg"
$b += "eyBzdGF0dXM6IDQwMyB9CiAgICAgICkKICAgIH0KCiAgICBpZiAoIVsnbGlzdGVkJywgJ2RyYWZ0"
$b += "J10uaW5jbHVkZXMoYXJ0d29yay5zdGF0dXMpKSB7CiAgICAgIHJldHVybiBOZXh0UmVzcG9uc2Uu"
$b += "anNvbigKICAgICAgICB7IGVycm9yOiAnQXJ0d29yayBpcyBhbHJlYWR5IGluIGF1Y3Rpb24gb3Ig"
$b += "c29sZCcgfSwKICAgICAgICB7IHN0YXR1czogNDA5IH0KICAgICAgKQogICAgfQoKICAgIC8vIENy"
$b += "ZWF0ZSBhdWN0aW9uCiAgICBjb25zdCB7IGRhdGE6IGF1Y3Rpb24sIGVycm9yOiBhdWNFcnJvciB9"
$b += "ID0gYXdhaXQgc3VwYWJhc2UKICAgICAgLmZyb20oJ2F1Y3Rpb25zJykKICAgICAgLmluc2VydCh7"
$b += "CiAgICAgICAgYXJ0d29ya19pZDogIGFydHdvcmtfaWQsCiAgICAgICAgc2VsbGVyX2lkOiAgIHBy"
$b += "b2ZpbGVJZCwKICAgICAgICByZXNlcnZlX2dicDogcmVzZXJ2ZV9nYnAsCiAgICAgICAgb3BlbnNf"
$b += "YXQ6ICAgIG9wZW5zX2F0LAogICAgICAgIGNsb3Nlc19hdDogICBjbG9zZXNfYXQsCiAgICAgICAg"
$b += "c3RhdHVzOiAgICAgICdsaXZlJywKICAgICAgfSkKICAgICAgLnNlbGVjdCgpCiAgICAgIC5zaW5n"
$b += "bGUoKQoKICAgIGlmIChhdWNFcnJvcikgewogICAgICByZXR1cm4gTmV4dFJlc3BvbnNlLmpzb24o"
$b += "CiAgICAgICAgeyBlcnJvcjogJ0ZhaWxlZCB0byBjcmVhdGUgYXVjdGlvbjogJyArIGF1Y0Vycm9y"
$b += "Lm1lc3NhZ2UgfSwKICAgICAgICB7IHN0YXR1czogNTAwIH0KICAgICAgKQogICAgfQoKICAgIC8v"
$b += "IFVwZGF0ZSBhcnR3b3JrIHN0YXR1cyB0byBpbl9hdWN0aW9uCiAgICBjb25zdCB7IGVycm9yOiB1"
$b += "cGRhdGVFcnJvciB9ID0gYXdhaXQgc3VwYWJhc2UKICAgICAgLmZyb20oJ2FydHdvcmtzJykKICAg"
$b += "ICAgLnVwZGF0ZSh7IHN0YXR1czogJ2luX2F1Y3Rpb24nIH0pCiAgICAgIC5lcSgnaWQnLCBhcnR3"
$b += "b3JrX2lkKQoKICAgIGlmICh1cGRhdGVFcnJvcikgewogICAgICBjb25zb2xlLmVycm9yKCdGYWls"
$b += "ZWQgdG8gdXBkYXRlIGFydHdvcmsgc3RhdHVzOicsIHVwZGF0ZUVycm9yKQogICAgfQoKICAgIC8v"
$b += "IEFwcGVuZCBwcm92ZW5hbmNlIGV2ZW50CiAgICBjb25zdCB7IGRhdGE6IGF3IH0gPSBhd2FpdCBz"
$b += "dXBhYmFzZQogICAgICAuZnJvbSgnYXJ0d29ya3MnKS5zZWxlY3QoJ3Byb3ZlbmFuY2UnKS5lcSgn"
$b += "aWQnLCBhcnR3b3JrX2lkKS5zaW5nbGUoKQogICAgaWYgKGF3KSB7CiAgICAgIGF3YWl0IHN1cGFi"
$b += "YXNlLmZyb20oJ2FydHdvcmtzJykudXBkYXRlKHsKICAgICAgICBwcm92ZW5hbmNlOiBbLi4uKGF3"
$b += "LnByb3ZlbmFuY2UgYXMgb2JqZWN0W10pLCB7CiAgICAgICAgICB0eXBlOiAnbGlzdGVkJywKICAg"
$b += "ICAgICAgIGRlc2NyaXB0aW9uOiAnTGlzdGVkIGZvciBhdWN0aW9uIG9uIEFydFVOREVSR1JPVU5E"
$b += "JywKICAgICAgICAgIGRhdGU6IG5ldyBEYXRlKCkudG9JU09TdHJpbmcoKS5zcGxpdCgnVCcpWzBd"
$b += "LAogICAgICAgIH1dCiAgICAgIH0pLmVxKCdpZCcsIGFydHdvcmtfaWQpCiAgICB9CgogICAgcmV0"
$b += "dXJuIE5leHRSZXNwb25zZS5qc29uKHsgYXVjdGlvbiB9LCB7IHN0YXR1czogMjAxIH0pCgogIH0g"
$b += "Y2F0Y2ggKGVycjogYW55KSB7CiAgICBjb25zb2xlLmVycm9yKCdBdWN0aW9uIHJvdXRlIHVuaGFu"
$b += "ZGxlZCBlcnJvcjonLCBlcnI/Lm1lc3NhZ2UgPz8gZXJyKQogICAgcmV0dXJuIE5leHRSZXNwb25z"
$b += "ZS5qc29uKAogICAgICB7IGVycm9yOiAnSW50ZXJuYWwgc2VydmVyIGVycm9yOiAnICsgKGVycj8u"
$b += "bWVzc2FnZSA/PyAndW5rbm93bicpIH0sCiAgICAgIHsgc3RhdHVzOiA1MDAgfQogICAgKQogIH0K"
$b += "fQo="
$bytes = [System.Convert]::FromBase64String($b)
$dir   = Join-Path (Get-Location) "src\app\api\auctions"
if (!(Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
$path  = Join-Path $dir "route.ts"
[System.IO.File]::WriteAllBytes($path, $bytes)
Write-Host ">> Auction route fixed" -ForegroundColor Green
Write-Host ""
Write-Host "Now try the Auction button again." -ForegroundColor Cyan
Write-Host "The error message will now tell you exactly what failed." -ForegroundColor Yellow
Write-Host ""