# Fix provenance null crash in auction route
# Usage: PowerShell -ExecutionPolicy Bypass -File .\fix_auction3.ps1

$b = ""
$b += "aW1wb3J0IHsgTmV4dFJlcXVlc3QsIE5leHRSZXNwb25zZSB9IGZyb20gJ25leHQvc2VydmVyJwpp"
$b += "bXBvcnQgeyBjcmVhdGVTZXJ2ZXJTdXBhYmFzZUNsaWVudCB9IGZyb20gJ0AvbGliL3N1cGFiYXNl"
$b += "L3NlcnZlcicKaW1wb3J0IHsgeiB9IGZyb20gJ3pvZCcKCmNvbnN0IENyZWF0ZUF1Y3Rpb25TY2hl"
$b += "bWEgPSB6Lm9iamVjdCh7CiAgYXJ0d29ya19pZDogIHouc3RyaW5nKCkudXVpZCgpLAogIHJlc2Vy"
$b += "dmVfZ2JwOiB6Lm51bWJlcigpLnBvc2l0aXZlKCksCiAgb3BlbnNfYXQ6ICAgIHouc3RyaW5nKCku"
$b += "bWluKDEpLAogIGNsb3Nlc19hdDogICB6LnN0cmluZygpLm1pbigxKSwKfSkKCmV4cG9ydCBhc3lu"
$b += "YyBmdW5jdGlvbiBQT1NUKHJlcXVlc3Q6IE5leHRSZXF1ZXN0KSB7CiAgdHJ5IHsKICAgIGNvbnN0"
$b += "IHN1cGFiYXNlID0gYXdhaXQgY3JlYXRlU2VydmVyU3VwYWJhc2VDbGllbnQoKQoKICAgIGNvbnN0"
$b += "IHsgZGF0YTogeyB1c2VyIH0sIGVycm9yOiBhdXRoRXJyb3IgfSA9IGF3YWl0IHN1cGFiYXNlLmF1"
$b += "dGguZ2V0VXNlcigpCiAgICBpZiAoYXV0aEVycm9yIHx8ICF1c2VyKSB7CiAgICAgIHJldHVybiBO"
$b += "ZXh0UmVzcG9uc2UuanNvbih7IGVycm9yOiAnVW5hdXRob3JpemVkJyB9LCB7IHN0YXR1czogNDAx"
$b += "IH0pCiAgICB9CgogICAgY29uc3QgeyBkYXRhOiBwcm9maWxlLCBlcnJvcjogcHJvZmlsZUVycm9y"
$b += "IH0gPSBhd2FpdCBzdXBhYmFzZQogICAgICAuZnJvbSgncHJvZmlsZXMnKS5zZWxlY3QoJ2lkLCBy"
$b += "b2xlcycpLmVxKCdhdXRoX3VzZXJfaWQnLCB1c2VyLmlkKS5zaW5nbGUoKQogICAgaWYgKHByb2Zp"
$b += "bGVFcnJvciB8fCAhcHJvZmlsZSkgewogICAgICByZXR1cm4gTmV4dFJlc3BvbnNlLmpzb24oeyBl"
$b += "cnJvcjogJ1Byb2ZpbGUgbm90IGZvdW5kJyB9LCB7IHN0YXR1czogNDA0IH0pCiAgICB9CiAgICBp"
$b += "ZiAoIXByb2ZpbGUucm9sZXMuaW5jbHVkZXMoJ2FydGlzdCcpKSB7CiAgICAgIHJldHVybiBOZXh0"
$b += "UmVzcG9uc2UuanNvbih7IGVycm9yOiAnT25seSBhcnRpc3RzIGNhbiBjcmVhdGUgYXVjdGlvbnMn"
$b += "IH0sIHsgc3RhdHVzOiA0MDMgfSkKICAgIH0KCiAgICBsZXQgYm9keTogdW5rbm93bgogICAgdHJ5"
$b += "IHsgYm9keSA9IGF3YWl0IHJlcXVlc3QuanNvbigpIH0KICAgIGNhdGNoIHsgcmV0dXJuIE5leHRS"
$b += "ZXNwb25zZS5qc29uKHsgZXJyb3I6ICdJbnZhbGlkIHJlcXVlc3QgYm9keScgfSwgeyBzdGF0dXM6"
$b += "IDQwMCB9KSB9CgogICAgY29uc3QgcGFyc2VkID0gQ3JlYXRlQXVjdGlvblNjaGVtYS5zYWZlUGFy"
$b += "c2UoYm9keSkKICAgIGlmICghcGFyc2VkLnN1Y2Nlc3MpIHsKICAgICAgcmV0dXJuIE5leHRSZXNw"
$b += "b25zZS5qc29uKAogICAgICAgIHsgZXJyb3I6IHBhcnNlZC5lcnJvci5lcnJvcnMubWFwKGUgPT4g"
$b += "ZS5tZXNzYWdlKS5qb2luKCcsICcpIH0sCiAgICAgICAgeyBzdGF0dXM6IDQwMCB9CiAgICAgICkK"
$b += "ICAgIH0KCiAgICBjb25zdCB7IGFydHdvcmtfaWQsIHJlc2VydmVfZ2JwLCBvcGVuc19hdCwgY2xv"
$b += "c2VzX2F0IH0gPSBwYXJzZWQuZGF0YQoKICAgIGNvbnN0IHsgZGF0YTogYXJ0d29yaywgZXJyb3I6"
$b += "IGFydHdvcmtFcnJvciB9ID0gYXdhaXQgc3VwYWJhc2UKICAgICAgLmZyb20oJ2FydHdvcmtzJyku"
$b += "c2VsZWN0KCdpZCwgc3RhdHVzLCBhcnRpc3RfaWQnKS5lcSgnaWQnLCBhcnR3b3JrX2lkKS5zaW5n"
$b += "bGUoKQogICAgaWYgKGFydHdvcmtFcnJvciB8fCAhYXJ0d29yaykgewogICAgICByZXR1cm4gTmV4"
$b += "dFJlc3BvbnNlLmpzb24oeyBlcnJvcjogJ0FydHdvcmsgbm90IGZvdW5kJyB9LCB7IHN0YXR1czog"
$b += "NDA0IH0pCiAgICB9CiAgICBpZiAoU3RyaW5nKGFydHdvcmsuYXJ0aXN0X2lkKS50cmltKCkgIT09"
$b += "IFN0cmluZyhwcm9maWxlLmlkKS50cmltKCkpIHsKICAgICAgcmV0dXJuIE5leHRSZXNwb25zZS5q"
$b += "c29uKHsgZXJyb3I6ICdZb3UgZG8gbm90IG93biB0aGlzIGFydHdvcmsnIH0sIHsgc3RhdHVzOiA0"
$b += "MDMgfSkKICAgIH0KICAgIGlmICghWydsaXN0ZWQnLCAnZHJhZnQnXS5pbmNsdWRlcyhhcnR3b3Jr"
$b += "LnN0YXR1cykpIHsKICAgICAgcmV0dXJuIE5leHRSZXNwb25zZS5qc29uKHsgZXJyb3I6ICdBcnR3"
$b += "b3JrIGlzIGFscmVhZHkgaW4gYXVjdGlvbiBvciBzb2xkJyB9LCB7IHN0YXR1czogNDA5IH0pCiAg"
$b += "ICB9CgogICAgY29uc3QgeyBkYXRhOiBhdWN0aW9uLCBlcnJvcjogYXVjRXJyb3IgfSA9IGF3YWl0"
$b += "IHN1cGFiYXNlCiAgICAgIC5mcm9tKCdhdWN0aW9ucycpCiAgICAgIC5pbnNlcnQoewogICAgICAg"
$b += "IGFydHdvcmtfaWQsCiAgICAgICAgc2VsbGVyX2lkOiAgIHByb2ZpbGUuaWQsCiAgICAgICAgcmVz"
$b += "ZXJ2ZV9nYnAsCiAgICAgICAgb3BlbnNfYXQsCiAgICAgICAgY2xvc2VzX2F0LAogICAgICAgIHN0"
$b += "YXR1czogJ2xpdmUnLAogICAgICB9KQogICAgICAuc2VsZWN0KCkKICAgICAgLnNpbmdsZSgpCgog"
$b += "ICAgaWYgKGF1Y0Vycm9yKSB7CiAgICAgIHJldHVybiBOZXh0UmVzcG9uc2UuanNvbigKICAgICAg"
$b += "ICB7IGVycm9yOiAnRmFpbGVkIHRvIGNyZWF0ZSBhdWN0aW9uOiAnICsgYXVjRXJyb3IubWVzc2Fn"
$b += "ZSB9LAogICAgICAgIHsgc3RhdHVzOiA1MDAgfQogICAgICApCiAgICB9CgogICAgLy8gVXBkYXRl"
$b += "IGFydHdvcmsgc3RhdHVzCiAgICBhd2FpdCBzdXBhYmFzZS5mcm9tKCdhcnR3b3JrcycpLnVwZGF0"
$b += "ZSh7IHN0YXR1czogJ2luX2F1Y3Rpb24nIH0pLmVxKCdpZCcsIGFydHdvcmtfaWQpCgogICAgLy8g"
$b += "QXBwZW5kIHByb3ZlbmFuY2Ug4oCUIHNhZmVseSBoYW5kbGUgbnVsbCBvciBub24tYXJyYXkgcHJv"
$b += "dmVuYW5jZQogICAgY29uc3QgeyBkYXRhOiBhdyB9ID0gYXdhaXQgc3VwYWJhc2UKICAgICAgLmZy"
$b += "b20oJ2FydHdvcmtzJykuc2VsZWN0KCdwcm92ZW5hbmNlJykuZXEoJ2lkJywgYXJ0d29ya19pZCku"
$b += "c2luZ2xlKCkKCiAgICBpZiAoYXcpIHsKICAgICAgY29uc3QgZXhpc3RpbmcgPSBBcnJheS5pc0Fy"
$b += "cmF5KGF3LnByb3ZlbmFuY2UpID8gYXcucHJvdmVuYW5jZSA6IFtdCiAgICAgIGF3YWl0IHN1cGFi"
$b += "YXNlLmZyb20oJ2FydHdvcmtzJykudXBkYXRlKHsKICAgICAgICBwcm92ZW5hbmNlOiBbLi4uZXhp"
$b += "c3RpbmcsIHsKICAgICAgICAgIHR5cGU6ICdsaXN0ZWQnLAogICAgICAgICAgZGVzY3JpcHRpb246"
$b += "ICdMaXN0ZWQgZm9yIGF1Y3Rpb24gb24gQXJ0VU5ERVJHUk9VTkQnLAogICAgICAgICAgZGF0ZTog"
$b += "bmV3IERhdGUoKS50b0lTT1N0cmluZygpLnNwbGl0KCdUJylbMF0sCiAgICAgICAgfV0KICAgICAg"
$b += "fSkuZXEoJ2lkJywgYXJ0d29ya19pZCkKICAgIH0KCiAgICByZXR1cm4gTmV4dFJlc3BvbnNlLmpz"
$b += "b24oeyBhdWN0aW9uIH0sIHsgc3RhdHVzOiAyMDEgfSkKCiAgfSBjYXRjaCAoZXJyOiBhbnkpIHsK"
$b += "ICAgIGNvbnNvbGUuZXJyb3IoJ0F1Y3Rpb24gcm91dGUgZXJyb3I6JywgZXJyPy5tZXNzYWdlID8/"
$b += "IGVycikKICAgIHJldHVybiBOZXh0UmVzcG9uc2UuanNvbigKICAgICAgeyBlcnJvcjogJ0ludGVy"
$b += "bmFsIHNlcnZlciBlcnJvcjogJyArIChlcnI/Lm1lc3NhZ2UgPz8gJ3Vua25vd24nKSB9LAogICAg"
$b += "ICB7IHN0YXR1czogNTAwIH0KICAgICkKICB9Cn0K"
$bytes = [System.Convert]::FromBase64String($b)
$dir   = Join-Path (Get-Location) "src\app\api\auctions"
if (!(Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
[System.IO.File]::WriteAllBytes((Join-Path $dir "route.ts"), $bytes)
Write-Host ">> Fixed provenance null crash" -ForegroundColor Green
Write-Host "Try the Auction button now." -ForegroundColor Cyan